### ISSUE TITLE
Installing tweak to overhaul without Compopack generates errors

### ISSUE THREAD

**Issue by darthmolen** [Misunderstood-Wookiee/Valmod-Overhaul-Tweaks#1] opened 2016-11-21 16:17 UTC
![20161121101533_1](https://cloud.githubusercontent.com/assets/533340/20490425/8ac3f492-afd3-11e6-99da-572d2855cf87.jpg)
![20161121101551_1](https://cloud.githubusercontent.com/assets/533340/20490426/8ad6688e-afd3-11e6-94c5-31b7e5e5619b.jpg)

Installing just overhaul without the compopack (I'm assuming these are POI in the compo-pack) generates these errors.

**Comment by Misunderstood-Wookiee** [comment] 2016-11-22 03:53
@darthmolen 
Do you mind informing me which release you have been using? 
For reference any version above the "first release" (v1.0.0) require you to install valmod and compo pack yourself as I no longer publish those mods along with the project this was intended as to bring the attention where it was deserved.

**Comment by Misunderstood-Wookiee** [comment] 2016-11-22 03:58
@darthmolen 

Oh, I see what happened here. It seems I have in-inadvertently updated the release branch from the dev branch so the changes are the latest but there the "readme" file was not merged so the information display is older than the version.  I will amend this problem right now,

**Closed** 2016-11-22 04:18 UTC
